version: "3.3"

services:
  checkmk:
    image: checkmk/${TYPE:-check-mk-free}:${VERSION:-2.1.0-latest}
    env_file: .env
    stdin_open: true 
    tty: true 
    ports:
      - target: 5000
        published: ${PORT:-5000}
        protocol: tcp
    tmpfs:
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - monitoring:/omd/sites
    networks:
      default: {}
    restart: always
networks:
  default:
    driver: ${NETWORK_MODE:-bridge}
    attachable: true
volumes:
  monitoring: {}

